[project]
include_dirs = [ "src" ]
build_dir    = "_build"
target_dir   = "_target"

[[target]]
name     = "income_tax"
modules  = [ "Income_tax", "Income_tax2" ]
tests    = [ ]  # Related test(s)
backends = [ "java" ]                        # Output language backends

